export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";

export const FETCH_INGRDIENTS_PENDING = "FETCH_INGRDIENTS_PENDING";
export const FETCH_INGRDIENTS_SUCCESS = "FETCH_INGRDIENTS_SUCCESS";
export const FETCH_INGRDIENTS_ERROR = "FETCH_INGRDIENTS_ERROR";

export const PURCHASE_BURGER_PENDING = "PURCHASE_BURGER_PENDING";
export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_ERROR = "PURCHASE_BURGER_ERROR";

export const PURCHASE_INT = "PURCHASE_INT";

export const FETCH_ORDER_PENDING = "FETCH_ORDER_PENDING";
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";
export const FETCH_ORDER_ERROR= "FETCH_ORDER_ERROR";

/** FOR SIGNIN AND SIGNUP */
export const SIGNIN_PENDING = "SIGNIN_PENDING"
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS"
export const SIGNIN_ERROR = "SIGNIN_ERROR"

export const SIGNUP_PENDING = "SIGNUP_PENDING"
export const SIGNUP_SUCCESS = "SIGNIN_SUCCESS"
export const SIGNUP_ERROR = "SIGNUP_ERROR"

export const AUTH_LOGOUT = "AUTH_LOGOUT"

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH"